### ISSUE TITLE
Jamepad does not work on RPI

### ISSUE THREAD

**Issue by teccheck** [williamahartman/Jamepad#11]
Is there a way to get Jamepad working on Armv7 systems like the Raspberry Pi 3?
I tried to build it on a raspberry pi, but it only gives me the x64 version of libjamepad.so.
If i try to run the Jar it gives me that error:

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.studiohartman.jamepad.ControllerManager.nativeInitSDLGamepad()Z
	at com.studiohartman.jamepad.ControllerManager.nativeInitSDLGamepad(Native Method)
	at com.studiohartman.jamepad.ControllerManager.initSDLGamepad(ControllerManager.java:79)
	at de.teccheck.controllertest.Main.main(Main.java:15)

Thanks

**Comment by electronstudio** [comment]
To do it _properly_ is going to be a pain, because Jnigen does not support ARM, so there is no way to build a release that works on Intel LInux and ARM Linux.

However you could probably hack together a build that works only Raspberry Pi.  It sounds like that is what you tried? The only problem now is that it is building a 64 bit .so?  In that case...

Edit JamepadNativesBuild.java.
Change `BuildTarget lin64 = BuildTarget.newDefaultTarget(TargetOs.Linux, true);`
to ` BuildTarget lin64 = BuildTarget.newDefaultTarget(TargetOs.Linux, false);`

Change `lin64.linkerFlags = "-shared -m64";`
to `lin64.linkerFlags = "-shared -m32";`

Run `./gradlew linuxnatives ; ./gradlew dist`

That should give a 32 bit Linux build.  I will try this myself when I get a Raspberry Pi.

**Comment by teccheck** [comment]
Thanks,
and yes i tried that.
I will try to hack it together.

**Comment by teccheck** [comment]
If i whant to compile it it gives that error:
(it's the same error with the x32 version)

:compileJava
:processResources UP-TO-DATE
:classes
:linuxNatives
Using system SDL     (arg: system-SDL2)   ON
Building for Windows (arg: build-windows) OFF
Building for Linux   (arg: build-linux)   ON
Building for OSX     (arg: build-OSX)     OFF

SDL version found: 2.0.9
##### GENERATING NATIVE CODE AND BUILD SCRIPTS #####
C/C++ for 'src/com/studiohartman/jamepad/ControllerIndex.java' up to date
Skipping 'src/com/studiohartman/jamepad/ControllerButton.java', no JNI code found.
Skipping 'src/com/studiohartman/jamepad/JamepadNativesBuild.java', no JNI code found.
C/C++ for 'src/com/studiohartman/jamepad/ControllerManager.java' up to date
Skipping 'src/com/studiohartman/jamepad/ControllerAxis.java', no JNI code found.
Wrote target 'Windows' build script 'jni/build-windows32.xml'
Wrote target 'Windows64' build script 'jni/build-windows64.xml'
Wrote target 'Linux64' build script 'jni/build-linux64.xml'
Wrote target 'MacOsX64' build script 'jni/build-macosx64.xml'
Wrote master build script 'jni/build.xml'

##### COMPILING NATIVES FOR LINUX #####
Executing 'ant -f /home/pi/Documents/Jamepad/jni/build-linux64.xml -Dhas-compiler=true clean postcompile'
Buildfile: /home/pi/Documents/Jamepad/jni/build-linux64.xml

clean:

precompile:

create-build-dir:
     [copy] Copying 3 files to /home/pi/Documents/Jamepad/jni/build/tmp/linux64

compile:
    [apply] g++: error: unrecognized command line option ‘-mfpmath=sse’
    [apply] g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
    [apply] g++: error: unrecognized command line option ‘-m64’

BUILD FAILED
/home/pi/Documents/Jamepad/jni/build-linux64.xml:88: apply returned: 1

Total time: 1 second

##### PACKING NATIVES INTO .JAR #####
Executing 'ant -f /home/pi/Documents/Jamepad/jni/build.xml pack-natives'
Buildfile: /home/pi/Documents/Jamepad/jni/build.xml

pack-natives:

BUILD SUCCESSFUL
Total time: 1 second

BUILD SUCCESSFUL

Total time: 23.794 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:dist

BUILD SUCCESSFUL

Total time: 21.471 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.14.1/userguide/gradle_daemon.html

Maybe i just whait for you to have a solution, i'm not that much into building and compiling.

Thanks

**Comment by electronstudio** [comment]
I have added code to do a cross-compiled ARM build https://github.com/williamahartman/Jamepad/tree/linuxbuildissues

Here is an ARM-only version of Jamepad I built:

[Jamepad-ARM.jar.zip](https://github.com/williamahartman/Jamepad/files/2646361/Jamepad-ARM.jar.zip)

I still don't have a Raspberry Pi so I haven't tested it.

**Comment by electronstudio** [comment]
I have remote access to a RPI3.  Previous Jar didn't work.  JniGen *does* have (incomplete) support for Arm and am now using it.  I have compiled on the RPI3 and it seems to run, although I can't connect controllers to verify it works.  Can someone do this?  Just do `java -jar JamepadRPI.jar` and it will run the tester.

Jar is here: https://github.com/williamahartman/Jamepad/releases/download/1.3/JamepadRPI.jar

However I can't get cross-compiling to work.  Therefore I can't easily build and I can't include RPI support in future releases.  In future you will have to either compile it yourself, or tell me how to cross-compile.

**Comment by teccheck** [comment]
It works!
The tester gives out some errors, but everything is working fine.
Really thanks man you're great.
