### ISSUE TITLE
Flip vertical axis

### ISSUE THREAD

**Issue by MrStahlfelge** [williamahartman/Jamepad#14]
Great to see here is life again.

If you plan to release a new major version, please consider to remove the vertical axis flip. 

https://github.com/williamahartman/Jamepad/blob/e1fadd1bd2a3a4b0bf0b7fd2653a15024b0811cb/src/com/studiohartman/jamepad/ControllerIndex.java#L214

It is a bit opinionated to differ from standards, had to implement a reflip in my lib to handle Jamepad. ;)

**Comment by electronstudio** [comment]
I’m reluctant to mess with the existing Jamepad API because I assume people are using it as is. I have another project where I completely replaced the API with a different one: 
https://github.com/electronstudio/sdl2gdx

**Comment by MrStahlfelge** [comment]
I can understand that. Of course people use it as it is, I also do so - there os no choice. ;-) 
In my opinion, it is okay to change that back with a new release and a clear release note.

**Comment by Gamebuster19901** [comment]
I'd prefer to keep it as is, as up being positive makes more sense. However if it's changed it isn't really that big of a deal.
