### ISSUE TITLE
Exception when gamecontrollerdb is placed in a subdirectory

### ISSUE THREAD

**Issue by MrStahlfelge** [williamahartman/Jamepad#15]
gamecontrollerdb.txt cannot be placed in a subdirectory. Call to 

            String mappingsPath = "jamepad/gamecontrollerdb.txt";
            controllerManager = new com.studiohartman.jamepad.ControllerManager(maxNumControllers, mappingsPath);

raises an Exception because of this line: 

https://github.com/williamahartman/Jamepad/blob/7366bb5926b6f48e360a664b1d6cfe4141c66f92/src/com/studiohartman/jamepad/ControllerManager.java#L306

So problem is that the temporary file can't be placed in a non-existant subdirectory. Instead of using path, a random string can be used.

**Comment by electronstudio** [comment]
What is the exception?

**Comment by MrStahlfelge** [comment]
java.nio.file.NoSuchFileException
I suspect it just happens on Windows.

**Comment by electronstudio** [comment]
Should be fixed by https://github.com/williamahartman/Jamepad/commit/7568a017970cf2c4381bf10a35734a8a565313dd let me know it it isn't.
