### ISSUE TITLE
Issue in class ControllerManager

### ISSUE THREAD

**Issue by RawadAlaryan** [williamahartman/Jamepad#16]
I think there is a bug preventing me to use the the vibrations in my XBox controller which is always at index 0, because of the if condition (index < controllers.length && index < 0)
which should be  index>=0.

public boolean doVibration(int index, float leftMagnitude, float rightMagnitude, int duration_ms) throws IllegalStateException {
        verifyInitialized();

        if(index < controllers.length && index < 0) {
            try {
                return controllers[index].doVibration(leftMagnitude, rightMagnitude, duration_ms);
            } catch (ControllerUnpluggedException e) {
                return false;
            }
        }

        return false;
    }

**Comment by electronstudio** [comment]
I think you're correct so I have changed it.  The bug has been there for a long time so I guess no-one has ever used this method.  Note that I have a spin-off project that has at least one user (me) so such bugs might get found more quickly.  https://github.com/electronstudio/sdl2gdx

**Comment by RawadAlaryan** [comment]
Hi Mr. Richard,
I just had a look to your new library.
I also think that u should fix the same bug inside the jamepad classes of ur new project. It is still there inside ControllerManager.

Best regards
Rawad

**Comment by electronstudio** [comment]
The Jamepad ControllerManager is not part of the published API of sdl2gdx. I thought it was harmless to keep the classes around for people who are were transitioning from Jamepad. But I guess I should delete them.
