### ISSUE TITLE
Initialize gamepad?

### ISSUE THREAD

**Issue by AlexanderRodecape** [williamahartman/Jamepad#23]
Hello,
I've had this library work with my code a few times, but for some reason a lot of the time when I call controllers.initSDLGamepad(); it just dies.  I set a breakpoint right after the call and it is never hit.

When I step into the called method, it gets down to this line, and never returns, no error is thrown: 
} else if (!this.nativeInitSDLGamepad()) {

I'm just making a quick java application and added the .jar as an external library in intellij.
Any ideas on what might be my problem?

Thanks

**Comment by electronstudio** [comment]
I can't promise any help since I moved on to sdl2gdx and don't use Jamepad any more.  However I suggest you post a complete copy of your project that fails to work.  (Even if I can't, someone else might then look at it.)

**Comment by AlexanderRodecape** [comment]
ah ok.  There really isn't anything to post, it's just a simple java application started on intellij and only has one class with this in it:

public ControllerManager controllers = new ControllerManager();
public Gamepad(){
    listen();
}
 private void listen(){
        //Print a message when the "A" button is pressed. Exit if the "B" button is pressed        
        // init
        controllers.initSDLGamepad();
        while(true) {
                      // do stuff
         }
  }

**Comment by electronstudio** [comment]
[intellijproj.zip](https://github.com/williamahartman/Jamepad/files/3612964/intellijproj.zip)

Here is an IntelliJ project with your code in it that works fine for me.  That doesn't really get us anywhere, which was the reason I asked for yours.

**Comment by AlexanderRodecape** [comment]
I get the same problem with the code you posted.  Well, I guess that means it's something with my environment. OK, thanks

**Comment by electronstudio** [comment]
what is your OS / Java version / game controller hardware?

**Comment by electronstudio** [comment]
suggest trying with latest release
