### ISSUE TITLE
How to actively trigger the key of the gamepad

### ISSUE THREAD

**Issue by chensiweipsp** [williamahartman/Jamepad#24]
I don't need to listen to the user, I just want to actively trigger the buttons in the game handle through the program.
How to do it
??

**Comment by electronstudio** [comment]
Sorry I don't understand the question.  If you mean you'd rather use event listeners than active polling, that is a feature in sdl2gdx https://electronstudio.github.io/sdl2gdx/uk/co/electronstudio/sdl2gdx/SDL2ControllerManager.html#addListener-com.badlogic.gdx.controllers.ControllerListener-
