### ISSUE TITLE
Controller2 left analog recognized as Controller1 d-pad

### ISSUE THREAD

**Issue by stouffers3** [williamahartman/Jamepad#8]
When two controllers are plugged in, the seconds controllers left analog stick is being recognized as the first controllers d-pad.
i.e.  In a 2 player game where the d-pad is used for movement, the second controller can move player1 using their left analog stick.

Controller being tested are XBOX one and XBOX 360

**Comment by electronstudio** [comment]
I have updated SDL to 2.0.9, does it fix this? https://github.com/electronstudio/Jamepad/

**Comment by electronstudio** [comment]
Please test with Jamepad 1.3 and re-open issue if necessary.
